// The virtual filesystem the terminal navigates — which sections exist and
// which files each one shows. No real files are read at runtime, except
// source-file entries, which are fetched from public/files/.
//
// This is the tree *data* only. Path traversal (cd, ls, cat resolution) lives
// in src/utils/filesystem.ts, which also grafts the blog/ directory on from the
// markdown in content/blog/.
//
// Content keys (FSFile.content) tell Cat.tsx what to render:
//   "about"                  → About component (contentMap lookup)
//   "source-file:/files/…"   → SourceViewer (fetches from public/files/)
//   "blog-post:<slug>"       → BlogPost reader (these entries are generated)
//
// filesChildren is generated by scripts/sync_files.py — do not hand-edit it.

import { FSDir, FSFile } from "./types";

// ── filesChildren ──────────────────────────────────────────────────────────────
// Managed by scripts/sync_files.py. Run `python3 scripts/sync_files.py` after
// adding or removing files from public/files/. Do not edit this block by hand.
const filesChildren: Record<string, FSDir | FSFile> = {
  "kalmarctf-2026": {
    type: "dir",
    children: {
      "crypto-RBG+": {
        type: "dir",
        children: {
          "chall.py": {
            type: "file",
            content: "source-file:/files/kalmarctf-2026/crypto-RBG+/chall.py",
          },
          "output.txt": {
            type: "file",
            content: "source-file:/files/kalmarctf-2026/crypto-RBG+/output.txt",
          },
        },
      },
    },
  },
  "lakectf-2025": {
    type: "dir",
    children: {
      "crypto-Conversation": {
        type: "dir",
        children: {
          Dockerfile: {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/Dockerfile",
          },
          "chall.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/chall.py",
          },
          "challenge.yml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/challenge.yml",
          },
          "compose.yaml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/compose.yaml",
          },
          "fancy.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/fancy.py",
          },
          "secret.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/secret.py",
          },
          "solve.sage": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/solve.sage",
          },
        },
      },
    },
  },
};
// ── end filesChildren ──────────────────────────────────────────────────────────

/**
 * The hand-maintained part of the tree.
 *
 * Key order matters — `ls` lists entries in declaration order (directories
 * first). blog/ is declared here with only its README; src/utils/filesystem.ts
 * appends one entry per post in content/blog/.
 */
export const staticTree: FSDir = {
  type: "dir",
  children: {
    "about.txt": { type: "file", content: "about" },
    blog: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "blog" },
      },
    },
    contact: {
      type: "dir",
      children: {
        "email.txt": { type: "file", content: "email" },
        "socials.txt": { type: "file", content: "socials" },
      },
    },
    education: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "education" },
      },
    },
    experience: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "experience" },
      },
    },
    projects: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "projects" },
      },
    },
    files: { type: "dir", children: filesChildren },
  },
};
