// Virtual filesystem used by the terminal.
//
// The tree is a plain TypeScript object — no real files are read at runtime
// (except source-file entries, which are fetched from /public/files/).
//
// Content keys (FSFile.content) tell Cat.tsx what to render:
//   "about"                  → About component (contentMap lookup)
//   "blog-post:<slug>"       → BlogPost reader (full-screen overlay)
//   "source-file:/files/…"   → SourceViewer (fetches from public/files/)
//
// filesChildren is generated by sync_files.py — do not hand-edit that block.

import { blogPosts } from "./blog";

/** A leaf node in the virtual filesystem. `content` is a routing key for Cat. */
export type FSFile = {
  type: "file";
  content: string;
};

/** An interior node in the virtual filesystem. */
export type FSDir = {
  type: "dir";
  children: Record<string, FSFile | FSDir>;
};

// blog/ children are generated from blogPosts so they stay in sync automatically.
const blogChildren: Record<string, FSFile> = {
  "README.txt": { type: "file", content: "blog" },
  ...Object.fromEntries(
    blogPosts.map(post => [
      `${post.slug}.md`,
      { type: "file", content: `blog-post:${post.slug}` },
    ])
  ),
};

// ── filesChildren ──────────────────────────────────────────────────────────────
// Managed by sync_files.py. Run `python3 sync_files.py` after adding or
// removing files from public/files/. Do not edit this block by hand.
const filesChildren: Record<string, FSDir | FSFile> = {
  "lakectf-2025": {
    type: "dir",
    children: {
      "crypto-Conversation": {
        type: "dir",
        children: {
          Dockerfile: {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/Dockerfile",
          },
          "chall.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/chall.py",
          },
          "challenge.yml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/challenge.yml",
          },
          "compose.yaml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/compose.yaml",
          },
          "fancy.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/fancy.py",
          },
          "secret.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/secret.py",
          },
          "solve.sage": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/solve.sage",
          },
        },
      },
    },
  },
};
// ── end filesChildren ──────────────────────────────────────────────────────────

export const filesystem: FSDir = {
  type: "dir",
  children: {
    "about.txt": { type: "file", content: "about" },
    blog: {
      type: "dir",
      children: blogChildren,
    },
    contact: {
      type: "dir",
      children: {
        "email.txt": { type: "file", content: "email" },
        "socials.txt": { type: "file", content: "socials" },
      },
    },
    education: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "education" },
      },
    },
    experience: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "experience" },
      },
    },
    projects: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "projects" },
      },
    },
    files: { type: "dir", children: filesChildren },
  },
};

/**
 * Walk a path array (e.g. ["~", "blog", "post.md"]) and return the node,
 * or null if any segment is missing or a file is traversed as a directory.
 * Index 0 is always "~" (the root) and is skipped.
 */
export const getNodeAtPath = (
  path: string[],
  fs: FSDir
): FSFile | FSDir | null => {
  let current: FSFile | FSDir = fs;
  for (let i = 1; i < path.length; i++) {
    if (current.type !== "dir") return null;
    const child: FSFile | FSDir | undefined = (current as FSDir).children[
      path[i]
    ];
    if (!child) return null;
    current = child;
  }
  return current;
};

/**
 * Resolve a single `cd` target relative to `cwd`.
 * Returns the new path array, or null if the target is not a directory.
 * Handles "~", "..", and ".".
 */
export const resolvePath = (
  cwd: string[],
  target: string | undefined,
  fs: FSDir
): string[] | null => {
  if (!target || target === "~") return ["~"];
  if (target === "..") return cwd.length > 1 ? cwd.slice(0, -1) : ["~"];
  if (target === ".") return [...cwd];

  const currentNode = getNodeAtPath(cwd, fs);
  if (!currentNode || currentNode.type !== "dir") return null;

  const child = (currentNode as FSDir).children[target];
  if (!child || child.type !== "dir") return null;

  return [...cwd, target];
};

/** Format a path array as a display string, e.g. ["~","blog"] → "~/blog". */
export const pathToString = (path: string[]): string => {
  if (path.length <= 1) return "~";
  return "~/" + path.slice(1).join("/");
};

/**
 * List the immediate children of a directory.
 * @param filter - if provided, return only "dir" or "file" entries.
 */
export const getDirChildren = (
  cwd: string[],
  fs: FSDir,
  filter?: "dir" | "file"
): Array<{ name: string; type: "dir" | "file" }> => {
  const node = getNodeAtPath(cwd, fs);
  if (!node || node.type !== "dir") return [];
  const entries: [string, FSFile | FSDir][] = Object.entries(
    (node as FSDir).children
  );
  return entries
    .filter(([, child]) => !filter || child.type === filter)
    .map(([name, child]) => ({ name, type: child.type as "dir" | "file" }));
};
