// Virtual filesystem used by the terminal.
//
// The tree is a plain TypeScript object — no real files are read at runtime
// (except source-file entries, which are fetched from /public/files/).
//
// Content keys (FSFile.content) tell Cat.tsx what to render:
//   "about"                  → About component (contentMap lookup)
//   "blog-post:<slug>"       → BlogPost reader (full-screen overlay)
//   "source-file:/files/…"   → SourceViewer (fetches from public/files/)
//
// filesChildren is generated by sync_files.py — do not hand-edit that block.

import { blogPosts } from "./blog";

/** A leaf node in the virtual filesystem. `content` is a routing key for Cat. */
export type FSFile = {
  type: "file";
  content: string;
};

/** An interior node in the virtual filesystem. */
export type FSDir = {
  type: "dir";
  children: Record<string, FSFile | FSDir>;
};

// blog/ children are generated from blogPosts so they stay in sync automatically.
const blogChildren: Record<string, FSFile> = {
  "README.txt": { type: "file", content: "blog" },
  ...Object.fromEntries(
    blogPosts.map(post => [
      `${post.slug}.md`,
      { type: "file", content: `blog-post:${post.slug}` },
    ])
  ),
};

// ── filesChildren ──────────────────────────────────────────────────────────────
// Managed by sync_files.py. Run `python3 sync_files.py` after adding or
// removing files from public/files/. Do not edit this block by hand.
const filesChildren: Record<string, FSDir | FSFile> = {
  "lakectf-2025": {
    type: "dir",
    children: {
      "crypto-Conversation": {
        type: "dir",
        children: {
          Dockerfile: {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/Dockerfile",
          },
          "chall.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/chall.py",
          },
          "challenge.yml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/challenge.yml",
          },
          "compose.yaml": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/compose.yaml",
          },
          "fancy.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/fancy.py",
          },
          "secret.py": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/secret.py",
          },
          "solve.sage": {
            type: "file",
            content:
              "source-file:/files/lakectf-2025/crypto-Conversation/solve.sage",
          },
        },
      },
    },
  },
};
// ── end filesChildren ──────────────────────────────────────────────────────────

export const filesystem: FSDir = {
  type: "dir",
  children: {
    "about.txt": { type: "file", content: "about" },
    blog: {
      type: "dir",
      children: blogChildren,
    },
    contact: {
      type: "dir",
      children: {
        "email.txt": { type: "file", content: "email" },
        "socials.txt": { type: "file", content: "socials" },
      },
    },
    education: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "education" },
      },
    },
    experience: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "experience" },
      },
    },
    projects: {
      type: "dir",
      children: {
        "README.txt": { type: "file", content: "projects" },
      },
    },
    files: { type: "dir", children: filesChildren },
  },
};

/**
 * Build a raw path array from a user-supplied string, relative to cwd.
 * Absolute paths (starting with "/") are anchored at root "~".
 * Relative paths are appended to cwd.
 * Does NOT normalize — pass the result to getNodeAtPath or normalizePath.
 */
export const buildPath = (cwd: string[], input: string): string[] =>
  input.startsWith("/")
    ? ["~", ...input.slice(1).split("/")]
    : [...cwd, ...input.split("/")];

/**
 * Normalize a path array by collapsing "." (stay) and ".." (parent) segments.
 * The first element is always "~" (root) and can never be popped.
 * Examples:
 *   ["~", "blog", ".."]          → ["~"]
 *   ["~", "blog", "..", "files"] → ["~", "files"]
 *   ["~", ".."]                  → ["~"]
 */
export const normalizePath = (path: string[]): string[] => {
  const result: string[] = [];
  for (const seg of path) {
    if (seg === "" || seg === ".") continue;
    if (seg === "..") {
      if (result.length > 1) result.pop(); // never pop past "~"
    } else {
      result.push(seg);
    }
  }
  return result.length > 0 ? result : ["~"];
};

/**
 * Walk a path array (e.g. ["~", "blog", "post.md"]) and return the node,
 * or null if any segment is missing or a file is traversed as a directory.
 * Index 0 is always "~" (the root) and is skipped.
 * Normalizes ".." and "." segments before walking.
 */
export const getNodeAtPath = (
  path: string[],
  fs: FSDir
): FSFile | FSDir | null => {
  const normalized = normalizePath(path);
  let current: FSFile | FSDir = fs;
  for (let i = 1; i < normalized.length; i++) {
    if (current.type !== "dir") return null;
    const child: FSFile | FSDir | undefined = (current as FSDir).children[
      normalized[i]
    ];
    if (!child) return null;
    current = child;
  }
  return current;
};

/**
 * Resolve a `cd` target relative to `cwd`.
 * Supports absolute paths (/blog), relative paths (files), and ".." / ".".
 * Returns the new normalized path array, or null if the target is not a directory.
 */
export const resolvePath = (
  cwd: string[],
  target: string | undefined,
  fs: FSDir
): string[] | null => {
  if (!target || target === "~") return ["~"];

  const normalized = normalizePath(buildPath(cwd, target));
  const node = getNodeAtPath(normalized, fs);
  if (!node || node.type !== "dir") return null;
  return normalized;
};

/** Format a path array as a display string, e.g. ["~","blog"] → "~/blog". */
export const pathToString = (path: string[]): string => {
  if (path.length <= 1) return "~";
  return "~/" + path.slice(1).join("/");
};

/**
 * List the immediate children of a directory.
 * @param filter - if provided, return only "dir" or "file" entries.
 */
export const getDirChildren = (
  cwd: string[],
  fs: FSDir,
  filter?: "dir" | "file"
): Array<{ name: string; type: "dir" | "file" }> => {
  const node = getNodeAtPath(cwd, fs);
  if (!node || node.type !== "dir") return [];
  const entries: [string, FSFile | FSDir][] = Object.entries(
    (node as FSDir).children
  );
  return entries
    .filter(([, child]) => !filter || child.type === filter)
    .map(([name, child]) => ({ name, type: child.type as "dir" | "file" }));
};
